### ISSUE TITLE
how to plot and write flie

### ISSUE THREAD

**Issue by cheriylan** [Js-Mim/rl_singing_voice#1]
run out scripts/exp_fe_test.py,but I don't know how to write a file,Thanks very much for your reply.

**Comment by Js-Mim** [comment]
Hi,

here: https://github.com/Js-Mim/rl_singing_voice/blob/master/scripts/exp_fe_test.py#L191
you can set "write_files=True". This will write the reconstructed .wav files. Similarly, "make_plots=True" will display the representation for the segments.

**Comment by cheriylan** [comment]
&nbsp; &nbsp; &nbsp; Thank you for your reply and inform!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Js-Mim/rl_singing_voice"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月5日(星期三) 晚上8:48
收件人:&nbsp;"Js-Mim/rl_singing_voice"<rl_singing_voice@noreply.github.com&gt;;
抄送:&nbsp;"岚岚"<1146626221@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Js-Mim/rl_singing_voice] how to plot and write flie (#1)





 
Closed #1.
