### ISSUE TITLE
Regarding source separation system implementation

### ISSUE THREAD

**Issue by blackpaintedman** [Js-Mim/rl_singing_voice#2]
Hi, nice work there!

Sorry for the noob question but do you have any advice on how to implement this representation in source seperation system? Like is there any framework I can get my hands on? Thank you!

**Comment by Js-Mim** [comment]
Hey @blackpaintedman , thanks for your interest!

There are various ways you could do that, depending on your goals. To throw a few directions:
1) You could use the learned representations, i.e., using only an optimized encoder (from our work),  on pairs of target source / mixture recordings and proceed as commonly done in supervised music source separation
2) You could add some additional layers to the whole model for learning representations and aim at separating the target source(s)
3) You could aim at directly training some discriminative models for separation and representation learning (some cool works done by ‪E. Tzinis & ‪S. Venkataramani either jointly or independently)
4) Some of the properties of the learned representation might come handy for unsupervised methods. 

For 1) and 2) here some frameworks, that not necessarily everything out there but my personal cup of tea:
https://github.com/dr-costas/mad-twinnet

https://github.com/sigsep/open-unmix-pytorch
