### ISSUE TITLE
how to use on mixture?

### ISSUE THREAD

**Issue by danielkorg** [Js-Mim/rl_singing_voice#3]
I think I have everything working so far, but not sure if I understand how to make it separate vocals from my own mixture. It seems to search for the dataset, but I want to try on my own files. Is there a way to do that? Thank you!

**Comment by Js-Mim** [comment]
What is it that you want to achieve and by what means?

**Comment by danielkorg** [comment]
Maybe I just misread what this was. I was thinking this would also do singing voice separation, but instead is just a framework that can help towards that goal. My bad.
